language: node_js

node_js:
  - "6"

before_install:
  # Setup the github deployment key for pushs
  - openssl aes-256-cbc -K $encrypted_3582d3969d58_key -iv $encrypted_3582d3969d58_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval $(ssh-agent -s)
  - ssh-add deploy_key

install:
  - npm install
  - npm run lint

script:
  - npm start
