language: node_js

node_js:
  - "node"

before_install:
  # Setup the github deployment key for pushs
  - openssl aes-256-cbc -K $encrypted_3582d3969d58_key -iv $encrypted_3582d3969d58_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval $(ssh-agent -s)
  - ssh-add deploy_key

install:
  - npm install
  - npm run lint

script:
  - if [ "$TRAVIS_BRANCH" == "deploy" ]; then
      npm start;
      cd cli-diff-selector;
      npm install;
      echo "[" > src/assets/versions.json;
      git branch -r | grep -v base | awk -F/ '/\/ng/{print "\""$3"\","}' | uniq | tr -d '\n' | sed 's/.$//' >> src/assets/versions.json;
      echo "]" >> src/assets/versions.json;
      cat src/assets/versions.json;
      export DEMO_DIST=$(pwd)/dist;
      node_modules/.bin/ng build --prod;
      cd ..;
      ./deploy.sh;
    else
      echo "Not on deploy branch";
    fi
