language: node_js

node_js:
  - "6"

before_install:
  # Setup the github deployment key for pushs
  - >-
    openssl aes-256-cbc
    -K $encrypted_xxxxxxxxxxxx_key
    -iv $encrypted_xxxxxxxxxxxx_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key

install:
  - npm install
  - npm run lint

script:
  - npm start
